server:
  port: 8443

#Spring相关
spring:
  #模板引擎
  thymeleaf:
    cache: false
  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ais?serverTimezone=UTC
    username: root
    password: 421571223
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual
    # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
    filters: stat,wall,log4j

#MyBatis
mybatis:
  type-aliases-package: com.oligizzz.mixueadmin.pojo
  mapper-locations: classpath:/mapper/**/*.xml
